# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mpos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mpos
  pod 'Alamofire', '~> 4.7'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'MSAL', '~> 0.5.0'
end
